### ISSUE TITLE
Host shows with 0 GiB RAM once discovered

### ISSUE THREAD

**Issue by reestr** [openshift/assisted-installer-agent#156]
Using assisted installer with guest VM on virtualbox, RAM is not correctly detected.  Cannot progress with install because minimum 16 GiB is not met, despite the guest having 16GiB.  See below:

<img width="1504" alt="Screenshot 2020-12-17 at 21 46 43" src="https://user-images.githubusercontent.com/4464624/102542493-2ee44400-40b2-11eb-9207-2b9095471823.png">

<img width="565" alt="Screenshot 2020-12-17 at 21 54 29" src="https://user-images.githubusercontent.com/4464624/102542702-75d23980-40b2-11eb-9413-6a6a6c5aeb57.png">

At the time of opening this I can't attach the agent logs because for some reason I can't ssh to the host, despite generating an ISO with my public key.

**Comment by omertuc** [comment]
/remove-lifecycle stale

@eliorerz did we make any progress with this?

**Comment by omertuc** [comment]
@eliorerz  ?

**Comment by omertuc** [comment]
Solved by #227
